# Elasticsearch Configuration for AI-powered Email Management Platform
# Version: 8.10+
# Purpose: Production configuration for high-availability monitoring cluster

#------------------------------------------------------------------------------
# Cluster Settings
#------------------------------------------------------------------------------
cluster:
  name: email-platform-monitoring
  routing:
    allocation:
      disk:
        threshold_enabled: true
        watermark:
          low: "85%"  # Warns when disk usage reaches 85%
          high: "90%" # Relocates shards when disk usage reaches 90%
          flood_stage: "95%" # Enforces read-only indices when disk usage reaches 95%

#------------------------------------------------------------------------------
# Node Settings
#------------------------------------------------------------------------------
node:
  name: ${HOSTNAME}
  roles: ["master", "data", "ingest", "ml"]
  attr:
    zone: ${ZONE}
  processors: 4
  # Enable memory locking to prevent swapping
  ml.max_open_jobs: 10
  data:
    aware: true

#------------------------------------------------------------------------------
# Discovery and Network Settings
#------------------------------------------------------------------------------
discovery:
  seed_hosts: ["es-node-1", "es-node-2", "es-node-3"]
  type: single-node
  zen:
    minimum_master_nodes: 2

network:
  host: 0.0.0.0
  publish_host: ${PUBLISH_HOST}
  bind_host: ${BIND_HOST}
  tcp:
    port: 9300
    compress: true

#------------------------------------------------------------------------------
# Memory and Heap Settings
#------------------------------------------------------------------------------
bootstrap:
  memory_lock: true

indices:
  memory:
    index_buffer_size: "30%"
    min_index_buffer_size: "96mb"
    max_index_buffer_size: "512mb"
  queries:
    cache:
      size: "15%"
  fielddata:
    cache:
      size: "20%"
  recovery:
    max_bytes_per_sec: "50mb"
  breaker:
    total:
      limit: "70%"
    fielddata:
      limit: "60%"
    request:
      limit: "40%"

#------------------------------------------------------------------------------
# Performance Settings
#------------------------------------------------------------------------------
thread_pool:
  write:
    size: 32
    queue_size: 1000
  search:
    size: 16
    queue_size: 1000
  get:
    size: 16
    queue_size: 1000

search:
  max_buckets: 10000
  max_concurrent_shard_requests: 5

#------------------------------------------------------------------------------
# Security Settings
#------------------------------------------------------------------------------
xpack:
  security:
    enabled: true
    transport:
      ssl:
        enabled: true
        verification_mode: certificate
        keystore:
          path: certs/elastic-certificates.p12
        truststore:
          path: certs/elastic-certificates.p12
    http:
      ssl:
        enabled: true
        keystore:
          path: certs/elastic-certificates.p12
        truststore:
          path: certs/elastic-certificates.p12

#------------------------------------------------------------------------------
# Monitoring Settings
#------------------------------------------------------------------------------
monitoring:
  collection:
    enabled: true
    interval: 30s
  history:
    duration: "7d"

#------------------------------------------------------------------------------
# Path Settings
#------------------------------------------------------------------------------
path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

#------------------------------------------------------------------------------
# Action and Circuit Breaker Settings
#------------------------------------------------------------------------------
action:
  destructive_requires_name: true
  auto_create_index: false

#------------------------------------------------------------------------------
# Gateway and Recovery Settings
#------------------------------------------------------------------------------
gateway:
  recover_after_nodes: 2
  recover_after_time: "5m"
  expected_nodes: 3

#------------------------------------------------------------------------------
# Snapshot Settings
#------------------------------------------------------------------------------
snapshot:
  max_concurrent_operations: 2

#------------------------------------------------------------------------------
# Logging Settings
#------------------------------------------------------------------------------
logger:
  level: INFO
  discovery: DEBUG
  deprecation: WARN