# Audit Policies Configuration
# Version: 1.0.0
# Dependencies:
# - @elastic/elasticsearch: 8.10.0 - ELK stack integration
# - aws-sdk: 2.1.1 - CloudWatch integration

# General Settings
general_settings:
  enabled: true
  environment: ${environment}
  region: ${aws_region}
  retention_period: ${log_retention_days}
  log_format: JSON
  compression: true
  sampling_rate: 100
  performance_mode: high_throughput
  backup_enabled: true

# Audit Event Configuration
audit_events:
  authentication:
    enabled: true
    events:
      - login_attempt
      - login_success
      - login_failure
      - logout
      - mfa_events
      - password_changes
      - token_validation
      - session_management
    severity: HIGH
    alert_threshold: 5
    correlation_enabled: true
    retention_priority: critical

  authorization:
    enabled: true
    events:
      - permission_changes
      - role_assignments
      - access_denials
      - privilege_escalations
      - policy_modifications
      - role_hierarchy_changes
    severity: CRITICAL
    alert_threshold: 3
    approval_required: true
    audit_trail_required: true

  data_access:
    enabled: true
    events:
      - email_read
      - email_write
      - attachment_access
      - context_modifications
      - pii_access
      - bulk_operations
    severity: MEDIUM
    pii_handling: true
    encryption_verification: true
    data_classification_required: true

  system_changes:
    enabled: true
    events:
      - configuration_changes
      - policy_modifications
      - system_updates
      - service_status_changes
      - infrastructure_modifications
      - security_control_changes
    severity: HIGH
    approval_required: true
    change_window_required: true
    rollback_plan_required: true

# Compliance Monitoring Configuration
compliance_monitoring:
  gdpr:
    enabled: true
    data_access_logging: true
    pii_tracking: true
    cross_border_transfers: true
    retention_checks: true
    consent_tracking: true
    data_subject_rights: true
    processor_monitoring: true

  soc2:
    enabled: true
    access_monitoring: true
    change_management: true
    incident_tracking: true
    availability_monitoring: true
    security_metrics: true
    vendor_management: true
    control_effectiveness: true

  hipaa:
    enabled: true
    phi_access_logging: true
    encryption_verification: true
    access_reviews: true
    minimum_necessary: true
    authorization_tracking: true
    disclosure_logging: true
    security_measures: true

# Logging Destinations
logging_destinations:
  elasticsearch:
    enabled: true
    endpoint: ${es_endpoint}
    index_pattern: audit-logs-${environment}-%{+YYYY.MM.dd}
    shards: 3
    replicas: 2
    refresh_interval: "1s"
    lifecycle_policy: hot-warm-cold
    compression_enabled: true

  cloudwatch:
    enabled: true
    log_group: /ai-email-platform/${environment}/audit-logs
    retention_days: 90
    metric_namespace: AuditMetrics
    export_enabled: true
    cross_account_sharing: false
    encryption_enabled: true

# Alert Configuration
alert_configuration:
  critical_events:
    channels:
      - email
      - slack
      - pagerduty
    response_time: "5m"
    escalation_policy: security_team
    notification_template: critical_alert
    retry_policy: exponential_backoff
    acknowledgment_required: true

  high_priority:
    channels:
      - email
      - slack
    response_time: "15m"
    escalation_policy: ops_team
    notification_template: high_priority_alert
    aggregation_window: "5m"
    suppression_enabled: true

  medium_priority:
    channels:
      - email
    response_time: "1h"
    escalation_policy: support_team
    notification_template: medium_priority_alert
    batch_notifications: true
    business_hours_only: true