# Encryption Configuration for AI Email Management Platform
# Version: 1.0.0
# Dependencies:
# - aws-encryption-sdk: 3.1.1
# - node-forge: 1.3.1

# Global Settings
environment: ${ENVIRONMENT}
aws_region: ${AWS_REGION}

# Data at Rest Encryption Configuration
data_at_rest:
  algorithm: AES-256-GCM
  key_management:
    provider: AWS_KMS
    key_rotation_period: 90d
    key_deletion_window: 30
    auto_rotation: true
    multi_region_keys: true
  
  storage_encryption:
    databases:
      postgresql:
        enabled: true
        kms_key_alias: alias/${environment}-rds-key
        backup_encryption: true
      mongodb:
        enabled: true
        kms_key_alias: alias/${environment}-docdb-key
        storage_encryption: true
      redis:
        enabled: true
        encryption_at_rest: true
        transit_encryption: true
    
    object_storage:
      s3:
        enabled: true
        encryption: AES256
        kms_key_alias: alias/${environment}-app-key
        versioning: true

# Data in Transit Encryption Configuration
data_in_transit:
  tls_configuration:
    minimum_version: TLS1.3
    preferred_cipher_suites:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
    certificate_management:
      provider: ACM
      renewal_window: 30d
      auto_renewal: true
      dns_validation: true
  
  api_encryption:
    enabled: true
    methods:
      - HTTPS
    minimum_key_length: 2048
    perfect_forward_secrecy: true
  
  service_mesh_encryption:
    enabled: true
    mtls:
      enabled: true
      certificate_rotation: 30d
      strict_validation: true

# Field-Level Encryption Configuration
field_level_encryption:
  enabled: true
  algorithm: ChaCha20-Poly1305
  sensitive_fields:
    - email_content
    - personal_information
    - authentication_tokens
    - api_keys
    - credentials
  key_management:
    rotation_period: 30d
    separate_keys_per_field: true

# Encryption Monitoring Configuration
monitoring:
  encryption_operations:
    logging:
      enabled: true
      log_level: INFO
      include_key_operations: true
      audit_trail: true
    alerts:
      key_rotation_failure:
        enabled: true
        severity: HIGH
        notification_channels:
          - email
          - slack
      encryption_failure:
        enabled: true
        severity: CRITICAL
        auto_remediation: true
  
  metrics:
    collection_enabled: true
    namespace: encryption_metrics
    dimensions:
      - service
      - encryption_type
      - key_id
      - region
      - operation_type
    retention_period: 90d

# Compliance Configuration
compliance:
  gdpr:
    enabled: true
    data_residency:
      regions:
        - eu-west-1
        - eu-central-1
      cross_border_transfer: false
      encryption_requirements: strong
    key_management:
      eu_specific_keys: true
      key_residency: eu-only
  
  hipaa:
    enabled: true
    encryption_strength: 256_bit
    key_backup_enabled: true
    audit_logging:
      enabled: true
      retention: 6y
  
  soc2:
    enabled: true
    audit_logging: true
    access_monitoring: true
    encryption_validation:
      periodic_testing: true
      test_frequency: 7d