# AWS KMS Encryption Provider version: v0.0.1
# This file contains sensitive configuration data encrypted using AWS KMS
# Rotation period: 90 days
# Access controlled via RBAC roles and service accounts
# Monitoring: Full audit logging and alerts enabled

---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: ai-email-platform
  labels:
    app: email-platform
    environment: production
    secret-rotation: enabled
    encryption: aws-kms
  annotations:
    encryption.aws.com/kms-key-id: arn:aws:kms:region:account:key/key-id
    secret.kubernetes.io/rotation-period: "90d"
    audit.kubernetes.io/level: READ_WRITE
    monitoring.kubernetes.io/alert-on-access: "true"
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERTIFICATE}
  tls.key: ${TLS_PRIVATE_KEY}
  jwt_secret: ${JWT_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: ai-email-platform
  labels:
    app: email-platform
    environment: production
    secret-rotation: enabled
    encryption: aws-kms
  annotations:
    encryption.aws.com/kms-key-id: arn:aws:kms:region:account:key/auth-key-id
    secret.kubernetes.io/rotation-period: "90d"
    rbac.authorization.kubernetes.io/autoupdate: "true"
    monitoring.kubernetes.io/alert-on-access: "true"
type: Opaque
data:
  AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: email-service-credentials
  namespace: ai-email-platform
  labels:
    app: email-platform
    environment: production
    secret-rotation: enabled
    encryption: aws-kms
  annotations:
    encryption.aws.com/kms-key-id: arn:aws:kms:region:account:key/email-key-id
    secret.kubernetes.io/rotation-period: "90d"
    monitoring.kubernetes.io/alert-on-access: "true"
type: Opaque
data:
  GMAIL_OAUTH_CLIENT_ID: ${GMAIL_OAUTH_CLIENT_ID}
  GMAIL_OAUTH_SECRET: ${GMAIL_OAUTH_SECRET}
  OUTLOOK_CLIENT_ID: ${OUTLOOK_CLIENT_ID}
  OUTLOOK_CLIENT_SECRET: ${OUTLOOK_CLIENT_SECRET}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: ai-email-platform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["api-gateway-secrets", "auth0-credentials", "email-service-credentials"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: ai-email-platform
subjects:
- kind: ServiceAccount
  name: email-platform-sa
  namespace: ai-email-platform
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-rotator
  namespace: ai-email-platform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "patch"]
  resourceNames: ["api-gateway-secrets", "auth0-credentials", "email-service-credentials"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rotator-binding
  namespace: ai-email-platform
subjects:
- kind: ServiceAccount
  name: secret-rotation-sa
  namespace: ai-email-platform
roleRef:
  kind: Role
  name: secret-rotator
  apiGroup: rbac.authorization.k8s.io