# Docker Compose configuration for AI Email Platform Web Frontend
# Version: 3.8 (Latest stable version with all required features)
version: '3.8'

services:
  web:
    image: node:20-alpine # Latest LTS Alpine-based Node.js image for minimal size
    container_name: ai-email-platform-web
    working_dir: /app
    command: npm run dev # Using Vite dev server with hot reload
    ports:
      - "3000:3000" # Main application port
      - "9229:9229" # Node.js debugging port
    volumes:
      - .:/app:delegated # Mount source code with delegated consistency
      - node_modules:/app/node_modules # Named volume for dependencies
    environment:
      - NODE_ENV=development
      - VITE_APP_ENV=development
      - VITE_API_URL=http://localhost:8080
      - VITE_ENABLE_ANALYTICS=false
      - VITE_LOG_LEVEL=debug
      - VITE_ENABLE_DEBUG=true
      - CHOKIDAR_USEPOLLING=true # Enable file watching in containers
      - WATCHPACK_POLLING=true # Enable webpack file watching
    networks:
      - ai-email-platform
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    sysctls:
      net.core.somaxconn: 1024
    restart: unless-stopped
    stop_grace_period: 30s
    init: true # Use tini for proper process management
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  ai-email-platform:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: ai-email-platform-net
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
        - subnet: 2001:db8::/64
    attachable: true

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind

x-common-labels: &common-labels
  com.example.project: "ai-email-platform"
  com.example.environment: "development"
  com.example.description: "AI Email Platform Web Frontend"
  com.example.maintainer: "DevOps Team"